spring:
    #DataSourse Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.134.253:3306/yupi
    username: root
    password: 12345678
    # session 失效时间
  session:
    timeout: 86400